SELECT
  x,
  SUM(x) OVER (ORDER BY x ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_sum,
  AVG(x) OVER (ORDER BY x ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS moving_avg
FROM UNNEST([10, 20, 30, 40, 50]) AS x
ORDER BY x
