WITH vals AS (
  SELECT 2 AS v, 'a' AS label UNION ALL
  SELECT CAST(NULL AS INT64), 'b' UNION ALL
  SELECT 1, 'c' UNION ALL
  SELECT CAST(NULL AS INT64), 'd' UNION ALL
  SELECT 3, 'e'
)
SELECT v, label FROM vals ORDER BY v ASC, label ASC
