WITH t AS (
  SELECT 'a' AS grp, 10 AS v UNION ALL
  SELECT 'a', 20 UNION ALL
  SELECT 'a', 20 UNION ALL
  SELECT 'b', 5 UNION ALL
  SELECT 'b', 15
)
SELECT
  grp, v,
  ROW_NUMBER() OVER (PARTITION BY grp ORDER BY v) AS rn,
  RANK() OVER (PARTITION BY grp ORDER BY v) AS rk,
  DENSE_RANK() OVER (PARTITION BY grp ORDER BY v) AS drk
FROM t
ORDER BY grp, v, rn
