WITH t AS (
  SELECT 10 AS v UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40
)
SELECT
  v,
  NTILE(2) OVER (ORDER BY v) AS tile,
  CAST(PERCENT_RANK() OVER (ORDER BY v) AS FLOAT64) AS pct_rank,
  CAST(CUME_DIST() OVER (ORDER BY v) AS FLOAT64) AS cume
FROM t
ORDER BY v
