WITH t AS (
  SELECT 2.0 AS v UNION ALL SELECT 4.0 UNION ALL SELECT 4.0 UNION ALL
  SELECT 4.0 UNION ALL SELECT 5.0 UNION ALL SELECT 5.0 UNION ALL
  SELECT 7.0 UNION ALL SELECT 9.0
)
SELECT
  CAST(STDDEV_POP(v) AS FLOAT64) AS stddev_pop,
  CAST(STDDEV_SAMP(v) AS FLOAT64) AS stddev_samp,
  CAST(VAR_POP(v) AS FLOAT64) AS var_pop,
  CAST(VAR_SAMP(v) AS FLOAT64) AS var_samp
FROM t
