WITH t AS (
  SELECT 'a' AS grp, 1 AS v UNION ALL
  SELECT 'a', 3 UNION ALL
  SELECT 'b', 2 UNION ALL
  SELECT 'b', 5
)
SELECT grp, v
FROM t
QUALIFY ROW_NUMBER() OVER (PARTITION BY grp ORDER BY v DESC) = 1
ORDER BY grp
